CREATE TABLE UserData (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(30) NOT NULL,
    value1 VARCHAR(10),
    value2 VARCHAR(10),
    reading_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

CREATE TABLE PostData (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Tittle VARCHAR(30) NOT NULL,
    content VARCHAR(512),
    author VARCHAR(30) NOT NULL,
    department VARCHAR(30) NOT NULL,
    reading_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)